logging:
  config: classpath:config/logback.xml
#logging:
#  file: /rule-engine-logs/${spring.application.name}/root.log
#  level: 
#    root: INFO
management:
  security:
    enabled: false
    
com:
  server:
    front: rule-engine-front
    front-url: 
    front-params: 
      x-micro-service-name: rule-engine-front
      x-name-space-code: default-code
##  数据源配置
rule:
  datasource:
    url: jdbc:mysql://172.31.64.14:3306?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: corepro01
    password: foxconn168!
    driverClassName: com.mysql.jdbc.Driver
#三方接口
thirdparty:
  core:
    pro:
      common: 
        topic-url: http://172.31.48.12:30750/corepro-common/kafkatopic
        uer-info-url: http://172.31.48.12:30750/corepro-common/userid
        user-database-url: http://172.31.48.12:30750/corepro-common/userDatabase
spring:
  #redis数据源配置
  redis:
    host: 172.31.64.4
    timeout: 1000
    port: 6379
    password: foxconn0
    pool:
      max-idle: 10
      max-active: 30
      max-wait: 18000
      min-idle: 0